### PR TITLE
Fix for pimatic v0.9.0

### PR DESCRIPTION
**Pull request by sweebee**
This works, don't know if its the right way but this will work.

### CODE REVIEW

**Comment by sweebee** [comment]
or should everything be:

```
@name = @config.name
@id = @config.id
```

**Comment by sweetpi** [comment]
> or should everything be:
> 
> @name = @config.name
> @id = @config.id

exactly.

**Comment by sweebee** [comment]
But this won't work in pimatic 0.8.  I get config error

**Comment by sweetpi** [comment]
> But this won't work in pimatic 0.8. I get config error

It shouldn't what error do you get?

**Comment by sweebee** [comment]
Yes indeed works, don't know what i did wrong.

**Comment by sweebee** [comment]
Could this one be merged? Then its ready for 0.9 :)

**Pull request merged**
